[constants]
auth_key = "dummy_key"
host = "127.0.0.1"
port = "8125"
setup_complete = false

gh_username = "dummy_gh_user"
gh_access_token = "ghp_xxxxxxxxxxxxxxxxxxxxxxx"

smtp_host = ""
smtp_port = ""
smtp_user = ""
smtp_pass = ""
smtp_from = ""
smtp_from_name = ""

twilio_sid = ""
twilio_token = ""
twilio_from = ""
